version: '3.8'
services:
  ms-app:
    container_name: ms-leganda
    restart: always
    image: '$REGISTRY/ms-leganda:latest'
    ports:
      - "27190:9090"
    networks:
      - applications-network
    environment:
      - "SPRING_PROFILES_ACTIVE=develop"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-zeeven.rule=Headers(`X-Host`, `api.leganda.chillo.fr`)"
      - "traefik.docker.network=applications-network"

networks:
  applications-network:
    external:
      name: applications-network

