version: '3.8'
services:
  ms-app:
    container_name: ms-leganda
    restart: always
    image: '$REGISTRY/ms-leganda:latest'
    ports:
      - "27190:9090"
    networks:
      - applications-network

networks:
  applications-network:
    external:
      name: applications-network

