server:
  host: http://api.leganda.chillo.fr
spring:
  data:
    mongodb:
      host: db-mongo
  mail:
      host: ${server.host}
      accountLink: ${server.host}/activer-mon-compte?code=
      activation-url:  ${server.host}/activate
      new-password-url:  ${server.host}/nouveau-mot-de-passe
      annonces-url:  ${server.host}/demenagements
      paiement-url:  ${server.host}/compte/paiement









