account:
  activation:
    send: true
    code: ""
server:
  port: 9090
  servlet:
    context-path: /api
  session.tracking-modes: 'cookie'
mongock:
  migration-scan-package:
  - com.cs.ganda.config.db.changelog
spring:
  application:
    name: ms-leganda
  spring:
    data:
      mongodb:
        database: leganda
        auto-index-creation: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mail:
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false

  sms:
    twilo:
      sid: ACe77e624544e47a28eed3a64b9f4a3034
      token: 201bc415fa1d15ec7e6f64772cd4fca0
      vaid: VA600e34ba66f214ed2f209b61584e310e
jwt:
  header: "Authorization"
  accessToken: "accessToken"
  refreshToken: "refreshToken"
  infos: "USER_INFOS"
  secret: "TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: "/login"
      refresh: "/refresh"

providers:
  mapbox:
    domain: "https://api.mapbox.com"
    places: "geocoding/v5/mapbox.places"
    country: "FR,CM,DE,US"
    access_token: "pk.eyJ1IjoiYWNoaWxsZW1ib3VndWVuZyIsImEiOiJja3Zvd3EzcmswaThkMnZrZ25iYmtveDBhIn0.pDR7pKL18d3iz5NoaRmWYg"
logging:
  pattern:
    file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    ROOT: INFO
    com.cs.ganda.: INFO
feign.client.config.default.loggerLevel: full
