management:
  trace:
    http.enabled: true
  endpoints:
    web:
      exposure:
        include: 'httptrace'

spring:
  data:
    mongodb:
      #username: rmongo
      #password: rambao
      database: db-leganda
      host: localhost
      port: 27117
      authentication-database: admin

  mail:
    host: localhost
    port: 28825
    activation-url: http://localhost:3000/activate
    new-password-url: http://localhost:3000/nouveau-mot-de-passe
    annonces-url: http://localhost:3000/demenagements
    paiement-url: http://localhost:3000/compte/paiement
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true


provider:
  stripe:
    secret-key: sk_test_51IGpLUHU7kKe8gmPt3PSfmD2Xbalw8eBuwRJGXwkrfxrTkvnHzvjPspcAjr3vLRTDMCpf52HUE0TOlyTE3CAUsaK007fmGY5bG
    public-key: pk_test_51IGpLUHU7kKe8gmPN8Mpm9zYXhi1L8PX2qPreTOKxBhOWqzQrojbyB25D98FMtdBZVMPSsQV2W9qygUOnAioKgaQ006TDtzpbG

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: TRACE

resources:
  images:
    folder: "/images/applications/leganda/images"
    host: "http://localhost:27191/images"
