account:
  activation:
    send: false
    code: "101010"

server:
  port: 9091
  servlet:
    context-path: /api
  session.tracking-modes: 'cookie'
mongock:
  migration-scan-package:
  - com.cs.ganda.config.db.changelog
spring:
  application:
    name: ms-leganda
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db-leganda
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: katyberte2@gmail.com
    password: srewjmweyjermxxi
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false
    accountLink: ${server.host}/activer-mon-compte?code=
    activation-url:  ${server.host}/activate
    new-password-url:  ${server.host}/nouveau-mot-de-passe
    annonces-url:  ${server.host}/annonces
    paiement-url:  ${server.host}/compte/paiement
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
  sms:
    twilo:
      sid: ACcbb01f55e3469ff5eea683ebc1aac50f
      token: e9af1368a0e58e3f423f755073a1ee90
      vaid: VAe62952bb863b850e20fb3caa82451131
jwt:
  header: "Authorization"
  accessToken: "accessToken"
  refreshToken: "refreshToken"
  infos: "USER_INFOS"
  secret: "TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: "/login"
      refresh: "/refresh"

providers:
  mapbox:
    domain: "https://api.mapbox.com"
    places: "geocoding/v5/mapbox.places"
    suggest: "search/v1/suggest"
    country: ""
    session_token: "3b43fe19-742a-4636-92a2-1d879fd2852e"
    #access_token: "pk.eyJ1IjoiYWNoaWxsZW1ib3VndWVuZyIsImEiOiJja3Zvd3EzcmswaThkMnZrZ25iYmtveDBhIn0.pDR7pKL18d3iz5NoaRmWYg"
    access_token: "pk.eyJ1IjoiYWNoaWxsZW1ib3VndWVuZyIsImEiOiJjbDdhMXJucWcwNGc1NDFycjhrZmoxbGVuIn0.sExmH0VyULHvnVju9Xl10Q"
logging:
  pattern:
    file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    ROOT: WARN
    com.cs.ganda.: WARN
feign.client.config.default.loggerLevel: BASIC
resources:
  images:
    folder: "/images/applications/leganda/images"
    host: "http://localhost:27191/images"
