server:
  host: http://api.leganda.chillo.fr
account:
  activation:
    send: false
    code: "101010"
spring:
  data:
    mongodb:
      host: db-mongo
      authentication-database: admin
  mail:
     host: mail-server

resources:
  images:
    folder: "images/leganda"
    host: "https://api.leganda.chillo.fr/assets"
