server:
  host: http://localhost:3000
account:
  activation:
    send: false
    code: "101010"
management:
  trace:
    http.enabled: true
  endpoints:
    web:
      exposure:
        include: 'httptrace'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin

  mail:
    host: localhost
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true


provider:
  stripe:
    secret-key: sk_test_51IGpLUHU7kKe8gmPt3PSfmD2Xbalw8eBuwRJGXwkrfxrTkvnHzvjPspcAjr3vLRTDMCpf52HUE0TOlyTE3CAUsaK007fmGY5bG
    public-key: pk_test_51IGpLUHU7kKe8gmPN8Mpm9zYXhi1L8PX2qPreTOKxBhOWqzQrojbyB25D98FMtdBZVMPSsQV2W9qygUOnAioKgaQ006TDtzpbG

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

resources:
  images:
    folder: "/images/applications/leganda/images"
    host: "http://localhost:27191/images"


