on:
  push:
    branches:
      #- develop
      - miseEnLigne
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'

permissions:
  contents: read

jobs:

  create-folder:
    name: Create folder
    runs-on: ubuntu-latest
    steps:
    - name: params
      run: echo ${{ github.ref_name }} ${{ github.sha }}
    - name: Create folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
        port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
        username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
        password: ${{ secrets.RECETTE_APPLICATIONS_PASSWPRD }}
        key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /opt/applications/leganda/ms-leganda
          sudo chmod ugo+rwx /opt/applications/leganda/ms-leganda

  copy-configs:
    name: "copy configs"
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
          port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
          username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
          password: ${{ secrets.RECETTE_APPLICATIONS_PASSWPRD }}
          key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/opt/applications/leganda/ms-leganda"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true clean compile package

      - name: rename
        run: |
          mv ./target/ms-leganda-0.0.1-SNAPSHOT.jar ./target/ms-leganda-${{ github.ref_name }}-${{ github.sha }}.jar
          ls -al target

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: ms-leganda
          path: ./target/ms-leganda-${{ github.ref_name }}-${{ github.sha }}.jar

  build-to-nexus:
    name: "Build to nexus"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ms-leganda
      - name: Check
        run: |
          ls -al

      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ secrets.NEXUS_HOSTNAME }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.cs artifactId=ms-leganda version=${{ github.ref_name }}-${{ github.sha }}
          assets: extension=jar
          filename: ms-leganda-${{ github.ref_name }}-${{ github.sha }}.jar

  dockerise-and-push-to-nexus:
    name: "dockerise-and-push-to-nexus"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ms-leganda
      - name: Check
        run: |
          ls -al
      - name: Update dockerfile
        run: |
          cat Dockerfile
          sed -i 's/APP_JAR/ms-leganda-${{ github.ref_name }}-${{ github.sha }}.jar/g' Dockerfile
          cat Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ${{ secrets.NEXUS_HOSTNAME }}/simachille/ms-leganda:${{ github.ref_name }}-${{ github.sha }}

      - name: push to nexus
        run: docker run ${{ secrets.NEXUS_HOSTNAME }}/simachille/ms-leganda:${{ github.ref_name }}-${{ github.sha }}

      - name: Login to Nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOSTNAME }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.NEXUS_HOSTNAME }}/simachille/ms-leganda-${{ github.ref_name }}-${{ github.sha }}

  # run-container:
  #   name: "Run container"
  #   runs-on: ubuntu-latest
  #   needs: [dockerize, copy-configs,use,build-to-nexus,dockerise-and-push-to-nexus]
  #   steps:
  #   - name: Run container
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
  #       port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
  #       username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
  #       password: ${{ secrets.RECETTE_APPLICATIONS_PASSWPRD }}
  #       key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
  #       script: |
  #         docker-compose -f /opt/applications/leganda/simachille/docker-compose.yml stop
  #         docker-compose -f /opt/applications/leganda/simachille/docker-compose.yml rm -f
  #         docker rmi simachille/simachille:develop -f
  #         docker-compose -f /opt/applications/leganda/simachille/docker-compose.yml up -d
